### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [klosstep/tc359_project10#1]
This is looking very nice! There's just one thing I'd like updated. As I mentioned for the previous project, I'd like this Git repository initialized from _within_ the project folder, rather than just outside of it. To fix this here, you can copy the contents of `rails_app1` to the folder `rails_app1` is in, then simply delete the `rails_app1` folder.

In the future, you'll be able to avoid this problem `cd`ing into the folder that `rails new` creates, _then_ typing `git init`.

Let me know if any of that doesn't make sense and I'll be happy to clarify. :smiley:

**Comment by klosstep** [comment]
all set.  https://github.com/klosstep/tc359_project10

**Comment by chrisvfritz** [comment]
:+1: Beautiful!
